# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: schedule-calendar
spec:
  enabled: true
  requires: ">=2.23.0"
  configMapName: schedule-calendar-settings
  settingName: schedule-calendar-settings
  author:
    name: 好名字
    website: https://sunnyhmz.top
  logo: logo.svg
  homepage: https://github.com/sunnyhmz7010/halo-plugin-schedule-calendar#readme
  repo: https://github.com/sunnyhmz7010/halo-plugin-schedule-calendar
  issues: https://github.com/sunnyhmz7010/halo-plugin-schedule-calendar/issues
  displayName: "日程日历"
  description: "提供前台日历页面、控制台事项管理和编辑器日程卡片的 Halo 插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/sunnyhmz7010/halo-plugin-schedule-calendar/blob/main/LICENSE"
